services:
  - type: web
    name: slg-face-recognition-api
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: API_SECRET
        sync: false
      - key: MODEL_PACK
        value: buffalo_l
      - key: DET_SIZE
        value: "640"
      - key: CTX_ID
        value: "-1"
